# Generated by Django 4.0.1 on 2023-07-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
